server:
  port: 8002
  servlet:
    context-path: /msvc-login

spring:
  application:
    name: msvc-login
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: msvc_login
      host: ec2-3-85-108-239.compute-1.amazonaws.com
      port: 27017

msvclogin:
  app:
    jwtCookieName: msvclogin
    jwtSecret: msvcLoginSecretKey
    jwtExpirationTime: 86400000
    origin: http://ec2-3-85-108-239.compute-1.amazonaws.com:9000
