server:
  port: 8002
  servlet:
    context-path: /msvc-login

spring:
  application:
    name: msvc-login
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: msvc_login_dev
      host: host.docker.internal
      port: 27017

msvclogin:
  app:
    jwtCookieName: msvclogin
    jwtSecret: msvcLoginSecretKey
    jwtExpirationTime: 86400000
    origin: http://localhost:9000